### ISSUE TITLE
【UI/UX】Design Issues Tracker for Swift/SwiftUI migration

### ISSUE THREAD

**Issue by Jerry23011** [tisfeng/Easydict#344]
This issue is used to track design-related issues in PRs that migrates Easydict to Swift/SwiftUI

- [x] Add copyright info to Settings, About tab
#309

- [x] In Settings, the button appears to experience lag when transitioning from other tabs to General
#326 

- [ ] ~~Scrolling in Settings, General tab feels laggy on 120Hz display~~ (SwiftUI performance issue)
#326 

- [x] Settings window often fails to appear in the front
#326

- [x] Add alert when user tries to hide menubar icon
#345 

- [ ] ~~Move `Check for Update` button to Settings, Advanced Tab~~
https://github.com/tisfeng/Easydict/pull/341#issuecomment-1901924275

- [ ] ~~Making tabs in Settings scrollable or not (General/Advanced/Privacy)~~
#359 
- [x] Some strings in Settings, Service tab are not localized
#311 
#324 
- [x] In Settings, Services tab, the list seems to wear off along with the elements when scrolling to the top/bottom
#326

**Comment by Jerry23011** [comment]
Closing this as most of the issues are resolved or consensus is reached.
